version: 2

jobs:
  build:
    docker:
      - image: cimg/rust:1.53.0

    steps:
      - checkout
      - run:
          name: Install Toolchain
          command: bash toolchain.sh
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Test Examples
          command: bash test_examples.sh
      
